### ISSUE TITLE
for...of output relies on Symbol.iterator and iterator.next()

### ISSUE THREAD

**Issue by 0x8890** [zenparsing/esdown#26]
This works in recent Node runtimes and web browsers, but `Symbol` isn't ES5. Is this a situation where I should bring my own Symbol polyfill?

**Comment by zenparsing** [comment]
Currently, you can bundle with esdown's ES6 polyfill library if you include the `-p` flag along with the `-r` flag

```
esdown - input.js output.js -r -p
```

(BTW, I need to update the README...)

But that will add esdown's runtime and ES6 polyfills to the global environment and will add quite a bit of code to your output.

For your use case (tapdance) you could either:

1.  Just not use for..of and use array.forEach instead, or
2.  In browsers, require that the user load a separate ES6 polyfill library, like esdown's polyfill or [core-js](https://github.com/zloirock/core-js) .

**Comment by zenparsing** [comment]
I've separated out the polyfill stuff into a separate package https://www.npmjs.com/package/esdown-polyfill which can be loaded independently, or you can use some smaller, more focused polyfill.
