### ISSUE TITLE
Node module output only

### ISSUE THREAD

**Issue by 0x8890** [zenparsing/esdown#31]
Right now, the boilerplate at the top of the output looks like this:

```
(function(fn, deps, name) { function obj() { return {} } if (typeof exports !== 'undefined') fn(require, exports, module); else if (typeof define === 'function' && define.amd) define(['require', 'exports', 'module'].concat(deps), fn); else if (typeof self !== 'undefined' && name) fn(obj, name === '*' ? self : (self[name] = {}), {}); else fn(obj, {}, {}); })(function(require, exports, module) { 'use strict'; function __load(p, l) { module.__es6 = !l; var e = require(p); if (e && e.constructor !== Object) e.default = e; return e; }
```

Not sure if the AMD stuff is needed. could there be an option to assume that we want to compile ES6 modules down to commonJS modules?

**Comment by zenparsing** [comment]
The whole thing looks like:

```js
    // CommonJS:
    "if (typeof exports !== 'undefined') " +
        "fn(require, exports, module); " +

    // AMD:
    "else if (typeof define === 'function' && define.amd) " +
        "define(['require', 'exports', 'module'].concat(deps), fn); " +

    // DOM global module:
    "else if (typeof self !== 'undefined' && name) " +
        "fn(obj, name === '*' ? self : (self[name] = {}), {}); " +

    // Hail Mary:
    "else " +
        "fn(obj, {}, {}); " +
```

I'm fine with taking out the AMD and the "Hail Mary" branches altogether.

**Comment by 0x8890** [comment]
Actually I was thinking that there should be an option to only use commonJS. the rationale is that I'd like to use browserify which assumes commonJS format and doesn't need all of the other branches.

**Comment by zenparsing** [comment]
Ah, cool.  Yeah, that seems like a good idea.

**Comment by zenparsing** [comment]
I'll need to modify the output to make it browserify-friendly.  Should be ready in the next couple of days.

**Comment by 0x8890** [comment]
:+1:

**Comment by zenparsing** [comment]
New module wrapper is better.  It does away with the AMD thing and only includes the wrapper if you've specified the "global" export name.  Otherwise, it's plain CJS.
