### ISSUE TITLE
Bundle option should rewrite require calls

### ISSUE THREAD

**Issue by 0x8890** [zenparsing/esdown#32]
When importing any module that calls `require`, I get `Error: Cannot find module`, due to the module being a dependency of the submodule. it should rewrite the value to be relative to the module in question, i.e. `node_modules/<MODULE>/node_modules/<SUBMODULE>`.

Alternatively, it should just completely skip non-relative paths, which would probably be the easiest way.

**Comment by zenparsing** [comment]
The bundling functionality is geared toward my atypical workflow and setup, so it probably needs a good rework.  (I think the translator just skips `require` calls in any case.)  It would probably be best to focus on non-bundling workflows first though, and approach this later.

**Comment by zenparsing** [comment]
New bundling format is much more like browserify.
