### ISSUE TITLE
Allow runtime module to be specified as external dependency

### ISSUE THREAD

**Issue by 0x8890** [zenparsing/esdown#33]
it would be nice to be able to specify where the runtime module is located. use case: I have 4 compiled files which all include the runtime at the top of the file, this obviously won't scale if I have a larger project with many files. what I would like:

```
esdown - lib/index.js dist/index.js -r dist/runtime.js
```

adding a path to the `-r` option would let esdown know not to include the raw text of the runtime but rather import it from that path. it would also be nice if esdown generates the compiled runtime at this path.

I think this is a blocker for adopting esdown on larger projects.

**Comment by zenparsing** [comment]
Agreed.  What I would like to do is to document the workflow(s) that we want to support before digging in to the code too much.  I'll post more on this later today.

**Comment by zenparsing** [comment]
The runtime can now be installed independently:  https://www.npmjs.com/package/esdown-runtime
